baseurl: /
title: 时间社THiS
languageCode: zh
paginate: '10'
theme: Mainroad
disqusShortname: ''
googleAnalytics: ''
summaryLength: truncate 20
Author:
  avatar: img/logo.png
  bio: 一个致力于推动历史社会科学和社会理论的思考、实践与对话的平台     
  name: 时间社THiS
menu:
  main:
    - name: 论坛 Forum
      url: /Forum/
    - name: 讲坛 Lecture
      url: /Lecture/
    - name: 工作坊 Workshop
      url: /Workshop/
    - name: 课纲 Syllabus
      url: /Syllabus/
    - name: 视频 Video
      url: /Video/
    - name: 有书斋 Book Talk
      url: /Booktalk/
    - name: 关于 ABOUT
      url: /about
Params:
  authorbox: yes
  description: This is the website for THiS
  logo:
    subtitle: Theory, History, Society
    image: "img/logo.png"
  mainSections:
    - Forum
    - Lecture
    - Workshop
    - Syllabus
    - Booktalk
  opengraph: yes
  thumbnail:
    list: true
  pager: yes
  post_meta:
    - date
    - categories
  readmore: no
  sidebar:
    home: right
    list: right
    single: right
    widgets:
      - search
      - recent
      - categories
      - taglist
      - social
  twitter_cards: yes
  widgets:
    recent_num: 5
    tags_counter: no
    social:
      twitter: THiS_TheHisSoc

