---
title: "时间社圆桌论坛 | 人文社会科学的历史感与理论感"
author: "时间社"
date: "2022-06-23"
output: html_document
thumbnail: "img/forum220623.png"

---
## 人文社会科学的历史感与理论感

历史学与社会科学正在经历着深度的交融。此种交融促使学者们超越历史客观经验与社会科学理论二分的隔阂，思考如何以新的方式理解历史与理论的关系问题。如果“历史”与“理论”并非只能在主客二分的界限中彼此对视，而是可以融汇于学者的精神生活，成为他们理解自我与世界的真切方式，那么，学者们对历史与理论可以有什么样的感受？这些感受从何而来？又如何推动他们展开研究？



这是“时间社THiS”组织的在线圆桌论坛之二。十二位不同学术背景的人文社科学者，将从各自研究经验出发讨论人文社科的历史感与理论感。欢迎大家关注、转发、参与！




## 上半场：北京时间6月25日晚上8:30-10:30

腾讯会议：669-739-901



主持人

**张颖，美国俄亥俄州立大学历史系副教授**




发言人

**曹寅，清华大学历史系副教授**

从毛淡棉回到吉大港：中国的区域国别研究需要去殖民吗？


**罗薇，北京大学政府管理学院助理教授**

从维基百科看社会学历史与理论之争


**刘永华，复旦大学历史系教授**

格尔兹书写社会史：重读《一个印尼市镇的社会史》（1965）


**王娟，加拿大麦吉尔大学政治系副教授**

路径依赖与历史研究


**张帆，北京大学社会学系助理教授**

时间中的文化：范畴与理想型





## 下半场：北京时间6月26日上午8:30-10:30

主持人

**罗祎楠，北京大学政府管理学院助理教授**


### 发言人

**裴电清，德国海德堡大学马克斯•韦伯社会学研究所博士候选人**

概念与历史：韦伯的社会科学方法论议题


**吴一庆，加拿大多伦多大学东亚研究系副教授**

为什么历史必须是反理论的：从“铁人料理”谈起


**董一格，美国纽约州立大学布法罗分校社会学系与全球性别研究系助理教授**

存在没有理论感的历史感吗？——总体性概念与历史研究的张力


**邱澎生，上海交通大学历史系特聘教授**

苹果树也该长出橘子吗？——明清经济法律史研究漫谈


**张泰苏，美国耶鲁大学法学院教授**

什么是合理的比较方法？