---
title: "时间社课纲｜清华大学严飞：《比较历史分析》"
author: "时间社"
output: html_document
date: 2022-10-15
#thumbnail: "img/yanfei.png"
categories: ["课纲-Syllabus"]
tags: ["课纲-Syllabus", "比较历史分析-Comparative-Histotry Analysis"]
---


# 时间社THiS课程大纲系列介绍

自2022年2月成立以来，时间社THiS（Theory, History, Society）致力于推动历史社会科学和社会理论的思考、实践与对话。今年暑假，我们推出时间社课纲系列，定期授权分享社会理论与方法实践、历史学与社会科学交叉领域的相关课程教纲，供有兴趣的朋友参考。推出这个栏目，既是知识和经验的分享，也缘于教中学的理念。我们希望借此获取对课程设计的反馈，欢迎大家在评论区留言，提出建议或问题，也殷切期盼学界同好联系我们，在本公号发布相关课程大纲。

联系邮箱：shijianshe2022@gmail.com


# 《比较历史分析》课程介绍

“历史想象力”对社会学的研究十分必要。历史社会学，并不仅仅只是简单的把社会学的理论与方法套在过去的档案资料、史料故事之上，而是更进一步从错综复杂的历史叙事中理出非故事性的过程，掌握其内在的因果关联以及不同时空脉络背后发挥的社会机制。在研究方法上，历史社会学采用解释（explanatory approach）而非解读（interpretative approach）的分析框架，透过历史比较研究方法构筑出历史发展的内在逻辑，编织历史的景观，并将内在的社会机制放置在另一个社会情境或者政治制度之下进行比较探讨，从而形成一个更优越的“经过社会科学认证过的故事”。



本课程将从比较历史社会分析的角度出发，以精读历史社会学代表性英文论文为主，在把握历史社会学三个理论思潮的发展动态基础上，深度研讨历史社会学领域内的重要话题，掌握比较历史研究方法，并进一步探讨历史社会学研究方法在中国社会的应用。

## 授课教授

严飞

清华大学

社会学系副教授

严飞，清华大学社会学系副教授，主要研究领域包括历史社会学、政治社会学、文化社会学，曾获美国亚洲研究协会（Association for Asian Studies）最佳研究生论文奖，在SSCI、CSSCI等重要学术期刊发表论文80余篇，著有英文著作Drivers of Innovation: Entrepreneurship, Education, and Finance in Asia (Stanford, CA: Shorenstein Asia-Pacific Research Center, 2022, with Yong Suk Lee), Understanding China through Big Data: Applications of Theory-oriented Quantitative Approaches (London: Routledge, 2022, with Yunsong Chen and Guangye He)，中文著作《悬浮：异乡人的都市生存》《穿透：像社会学家一样思考》《学问的冒险》《城市的张望》《我要的香港》等。

# 比较历史分析

第一周：历史、社会与历史社会学

➤ Skocpol, Theda. 1984. “Sociology’s historical imagination.” Pp. 1–21 in Theda Skocpol (ed.). Vision and Method in Historical Sociology. New York: Cambridge University Press.

➤ Sewell, William. 2005. Logics of History: Social Theory and Social Transformation. Chicago, IL: University of Chicago Press, chapter 1, “Theory, history and social science”.

➤ Chen, Yunsong and Fei Yan. 2016. “Centuries of sociology in millions of books.” The Sociological Review 64(4), 872–893.

第二周：历史社会学的三波思潮

➤Adams, Julia, Elisabeth S. Clemens and Ann Shola Orloff. 2005. “Introduction: Social theory, modernity, and the three waves of historical sociology.” Pp. 1–72 in Julia Adams, Elisabeth S. Clemens, and Ann Shola Orloff (eds.). Remaking Modernity: Politics and Processes in Historical Sociology. Durham: Duke University Press. 

➤Skocpol, Theda. 1976. “France, Russia, China: A structural analysis of social revolutions.” Comparative Studies in Society and History 18(2), 175–210.

➤Calhoun, Craig. 1996. “The rise and domestication of historical sociology.” Pp. 305–337 in Terrence J. McDonald. (ed.). The Historic Turn in the Human Sciences. Ann Arbor, MI: University of Michigan Press.

➤Mayrl, Damon and Nicholas Hoover Wilson. 2020. “What do historical sociologists do all day? Analytic architectures in historical sociology.” American Journal of Sociology 125(5), 1345–1394.

➤Zhang, Yang. 2019. “Thinking counterfactual sequentially: A processual view of counterfactual in historical sociology.” Journal of Historical Sociology 32, e15–e21.

第三周：历史社会学研究方法（1）：宏观历史比较 

➤Mahoney, James. 2004. “Comparative-historical methodology.” Annual Review of Sociology 30, 81–101.

➤Streeck, Wolfgang. 2015. “Comparative-historical analysis: Past, present, future.” Pp. 264–288 in James Mahoney and Kathleen Thelen (eds.). Advances in Comparative-Historical Analysis. New York: Cambridge University Press.

➤Brustein, William 1988. “The political geography of Belgian fascism: The case of Rexism.” American Sociological Review 53(1), 69–80.

➤Stinchcombe, Arthur L. 1994. “Freedom and oppression of slaves in the eighteenth-Century Caribbean.” American Sociological Review 59(6), 911–929.

第四周：历史社会学研究方法（2）：

档案、地方志、口述史、社会记忆

➤ Guo, Yuhua and Harriet Evans. 2009. “Making history from everyday life of common people: The oral history studies in a Chinese village.” Polish Sociological Review 167, 399–413.

➤ Olick, Jeffrey K. and Joyce Robbins. 1998. “Social memory studies: From ‘collective memory’ to the historical sociology of mnemonic practices.” Annual Review of Sociology 24, 105–140.

➤ Yang, Wenqi and Fei Yan. 2017. “The annihilation of femininity in Mao’s China: Gender inequality of sent-down youth during the Cultural Revolution.” China Information 31(1), 63–83.

➤ Walder, Andrew and Yang Su. 2003. “The Cultural Revolution in the countryside: Scope, timing and human impact.” The China Quarterly 173, 74–99.

第五周：历史社会学研究方法（3）：

定量模型、大数据与量化历史

➤Shorter, Edward and Charles Tilly. 1971. “The shape of strikes in France, 1830–1960.” Comparative Studies in Society and History 13(1), 60–86.

➤Lodhi, Abdul Qaiyum and Charles Tilly. 1973. “Urbanization, crime, and collective violence in 19th-century France.” American Journal of Sociology 79(2), 296–318.

➤Acemoglu, Daron, Davide Cantoni, Simon Johnson and James A. Robinson. 2011. “The consequences of radical reform: The French Revolution.” American Economic Review 101, 3206–3387.

➤Chen, Yunsong, Fei Yan and Yi Zhang. 2017. “Local name, global fame: The international visibility of Chinese cities in modern times.” Urban Studies 54(11), 2652–2668.

➤Chen, Yunsong and Fei Yan. 2018. “International visibility as determinants of foreign direct investment: An empirical study of Chinese provinces.” Social Science Research 76, 23–39.

第六周：历史事件的扩散模型分析

➤Conell, Carol and Samuel Cohn. 1995. “Learning from other people’s actions: Environmental variation and diffusion in French coal mining strikes, 1890–1935.” American Journal of Sociology 101(2), 366–403.

➤Tolnay, Stewart E., Glenn Deane and E. M. Beck. 1996. “Vicarious violence: Spatial effects on Southern Lynchings, 1890–1919.” American Journal of Sociology 102(3), 788–815.

➤Walder, Andrew and Qinglian Lu. 2017. “The dynamics of collapse in an authoritarian regime: China in 1967.” American Journal of Sociology 122(4), 1144–1182.

➤Biggs, Michael. 2003. “Positive feedback in collective mobilization: The American strike wave of 1886.” Theory and Society 32(2), 217–254.

➤Biggs, Michael. 2005. “Strikes as forest fires: Chicago and Paris in the late nineteenth century.” American Journal of Sociology 110(6), 1684–1714.

➤Xu, Hongwei and Geng Tian. 2020. “Is lying contagious? Spatial diffusion of high-yield “satellites” during China’s Great Leap Forward.” American Journal of Sociology 126(3), 632–672.

第七周：历史事件的事件过程分析

➤Falleti, Tulia G. and James Mahoney. 2015. “The comparative sequential Method.” Pp. 211–239 in James Mahoney and Kathleen Thelen (eds.). Advances in Comparative-Historical Analysis. New York: Cambridge University Press.

➤Sewell, William. 1996a. “Three temporalities: Toward an eventful sociology.” Pp. 245–280 in Terrance J. McDonald (ed.). The Historic Turn in the Human Sciences. Ann Arbor, MI: University of Michigan Press.

➤Sewell, William. 1996b. “Historical events as transformation of structures: Inventing revolution at the Bastille.” Theory and Society 25(6), 841–881.

➤Ermakoff, Ivan. 2015. “The structure of contingency.” American Journal of Sociology 121(1): 64–125.

➤Zhang, Yang. 2021. “Why elites rebel: Elite insurrections during the Taiping civil war in China.” American Journal of Sociology 127(1): 60–101.

第八周：历史事件的社会网分析

➤Gould, Roger V. 1991. “Multiple networks and mobilization in the Paris Commune, 1871.” American Sociological Review 56, 716–729.

➤Gould, Roger V. 1993. “Trade cohesion, class unity, and urban insurrection: Artisanal activism in the Paris Commune.” American Journal of Sociology 98(4), 721–754.

➤Gould, Roger V. 1996. “Patron-client ties, state centralization, and the Whiskey Rebellion.” American Journal of Sociology 102(2), 400–429. 

➤Kim, Hyojoung and Steven Pfaff. 2012. “Structure and dynamics of religious insurgency: Students and the spread of the Reformation.” American Sociological Review 77(2), 188–215.

➤Hillmann, Henning. 2008. “Mediation in multiple networks: Elite mobilization before the English Civil War.” American Sociological Review 73(3), 426–454.

第九周：战争与国家形成

➤Wimmer, Andreas and Brian Min. 2006. “From empire to nation-state: Explaining wars in the modern world, 1816–2001.” American Sociological Review 71(6), 867–897.

➤Dincecco, Mark and Yuhua Wang. 2018. “Violent conflict and political development over the long run: China versus Europe.” Annual Review of Political Science 21, 341–358.

➤Mann, Michael. 2018. “Have wars and violence declined?” Theory and Society 47, 37–60.

➤Kiser, Edgar and Yong Cai. 2003. “War and bureaucratization in Qin China: Exploring an anomalous case.” American Sociological Review 68(4), 511–539.

➤Zhao, Dingxin. 2004. “Comment on Kiser and Cai.” American Sociological Review 69(4), 603–607.

➤Kiser, Edgar and Yong Cai. 2004. “Reply to Zhao.” American Sociological Review 69(4), 608–612.

第十周：权力与国家治理

➤He, Wenkai. 2015. “Public interest and the financing of local water control in Qing China, 1750–1850.” Social Science History 39(3), 409–430.

➤Zhang, Changdong. 2017. “A fiscal sociological theory of authoritarian resilience.” Sociological Theory 35(1), 39–63.

➤Biggs, Michael. 1999. “Putting the state on the map: Cartography, territory, and European state formation.” Comparative Studies in Society and History 41(2), 374–411.

➤Hung, Ho-fung. 2009. “Cultural strategies and the political economy of protest in Mid-Qing China, 1740–1839.” Social Science History 33(1), 75–115.

➤Tong, James 1988. “Rational outlaws: Rebels and bandits in the Ming Dynasty, 1368–1644.” Pp 98–128 in Michael Taylor (ed.). Rationality and Revolution. New York: Cambridge University Press.

第十一周：历史运动中的挣扎与选择 

➤Markoff, John and Gilbert Shapiro. 1985. “Consensus and conflict at the onset of revolution: A quantitative study of France in 1789.” American Journal of Sociology 91(1), 28–53.

➤Traugott, Mark. 1980. “Determinants of political orientation: Class and organization in the Parisian insurrection of June 1848.” American Journal of Sociology 86(1), 32–49.

➤Walder, Andrew. 2006. “Ambiguity and choice in political movements: The origins of Beijing Red Guard factionalism.” American Journal of Sociology 112(3), 710–750.

➤Yan, Fei. 2015. “Rival rebels: The political origins of Guangzhou’s mass factions in 1967.” Modern China 41(2), 168–196.

第十二周：历史运动中的转换与招募

➤Sun, Yanfei. 2017. “The rise of Protestantism in post-Mao China: State and religion in historical perspective.” American Journal of Sociology 122(6), 1664–1725.

➤Xu, Xiaohong. 2013. “Belonging before believing: Group ethos and bloc recruitment in the making of Chinese communism.” American Sociological Review 78(5), 773–796.

➤Kane, Danielle and June Mee Park. 2009. “The puzzle of Korean Christianity: Geopolitical networks and religious conversion in early twentieth‐century East Asia.” American Journal of Sociology 115(2), 365–404.

➤Walder, Andrew. 2016. “Rebellion of the cadres: The 1967 implosion of the Chinese party-state.” The China Journal 75, 102–120.

第十三周：革命、控制与暴力

➤ Slater, Dan and Nicholas Rush Smith. 2016. “The power of counterrevolution: Elitist origins of political order in postcolonial Asia and Africa.” American Journal of Sociology 121(5), 1472–1516. 

➤ Bergemann, Patrick. 2017. “Denunciation and social control.” American Sociological Review 82(2), 384–406.

Walder, Andrew. 2014. “Rebellion and repression in China, 1966–1971.” Social Science History 38(3/4), 513–539.

➤ Walder, Andrew and James Chu. 2020. “Generating a violent insurgency: China’s factional warfare of 1967–1968.” American Journal of Sociology 126(1), 99–135.

➤ Rozenas, Arturas, Sebastian Schutte and Yuri Zhukov. 2017. “The political legacy of violence: The long-term impact of Stalin’s repression in Ukraine.” The Journal of Politics 79(4), 1147–1161.

➤ Wang, Yuhua. 2021. “The political legacy of violence during China’s Cultural Revolution.” British Journal of Political Science 51(2), 463–487.

第十四周：学期总结

第十五周：考试周

