---
title: "时间社课纲｜加州大学郑小威:《中国史学史：晚近帝国与现代中国》"
author: "时间社"
date: "2022-08-27"
thumbnail: "img/zhengxiaowei.png"
output: html_document
categories: ["课纲-Syllabus"]
tags: ["课纲-Syllabus","比较历史分析-Comparative-Histotry Analysis"]
---

## 时间社THiS课程大纲系列介绍

自2022年2月成立以来，时间社THiS（Theory, History, Society）致力于推动历史社会科学和社会理论的思考、实践与对话。今年暑假，我们推出时间社课纲系列，定期授权分享社会理论与方法实践、历史学与社会科学交叉领域的相关课程教纲，供有兴趣的朋友参考。推出这个栏目，既是知识和经验的分享，也缘于教中学的理念。我们希望借此获取对课程设计的反馈，欢迎大家在评论区留言，提出建议或问题，也殷切期盼学界同好联系我们，在本公号发布相关课程大纲。



联系邮箱：shijianshe2022@gmail.com


##《中国史学史：晚近帝国与现代中国》

## 课程介绍

史学史是历史系研究生的一门必修课。它的目的是使研究生能够了解相关的领域中的重要作品和学派，理解不同范式和社科理论对史学研究的影响，并且学会细读文本，领悟前辈史家运用材料和理论的方式及其具体的论证过程。本课程的设置有三个宗旨：第一，了解历史学领域中的关键作品和学派。第二，理解影响历史学思考的重要范式和理论。第三，读懂历史学家如何运用材料，进行论证，并达到自己的结论。



加州大学圣巴巴拉校区的中国史研究小组采取联合培养的形式。来自早期古代史，中古史和近现代史的研究生们被三位分属不同时段的老师（早期古代史的Anthony Barbieri，中古史的Ya Zuo，近现代史的Xiaowei Zheng）联合指导，所有学生都要必选三位老师的史学史课程，从而使学生们打通对整个中国史的理解。我们选择的阅读涵盖北美中国史学家，中国、日本的史学家以及欧洲汉学家的作品。在纵深和广度上，训练学生打开视野，看到不同学术脉络的下的学术成果和史学思维方式。



《中国史学史：晚近帝国与现代中国》是郑小威教授为研究生开设的史学史研讨课，也是三部曲中的最后一部。课程每周一次，每次三小时，以讨论为主。课程从概括阅读内容开始，从而保证所以学生对阅读理解的准确；之后自由讨论，内容包括阅读作品的论点、材料、语境、政治、范式。期间，穿插入方法论和理论的讨论。



具体而言，本课的阅读以三个大的主题展开：第一，什么是“中国”？讨论民族，族群，民族国家，认同等问题。第二，“中国”与“西方”。讨论一些领域中有影响力的范式和作品。第三，现代中国的具体样貌。讨论地方史，城市史，情感史，科学史，医学史。总体来说，这既是一门知识积累的课程，也是一门训练思辨能力的课程。这些对于作品理解和对于思考的训练最终会体现在一篇10-15页左右的史学史论文中。

## 授课教授

郑小威，加州大学圣芭芭拉校区历史系副教授，加州大学圣地亚哥校区历史学博士。研究领域为清代的地方史以及清末民初新型的政治文化（共和主义和民族主义）的兴起。研究兴趣包括革命史，特别是革命、立宪和民主化的比较研究。第一本书《民权政治与中国辛亥革命》是一部对于发生在地方的1911年革命的细致研究。目前正在写作的第二本书暂定名为《立宪主义在中国》。这本书探究20世纪近代中国的政治话语，具体包括民权、人民主权、共和主义与立宪主义在中国的历史。其他研究成果发表在中英德日文杂志和书籍。


## 中国史学史：晚近帝国与现代中国 Historiography of Late Imperial and Modern China


### Course Description

This seminar is on the scholarship of Late Imperial and Modern China. It seeks to explore this important field of historical research by reading scholarly works. This course guides you—graduate students in History and East Asian Studies—through the writing of a substantial historiographical paper. Upon finishing this class, you will become familiar with central topics and prevalent trends in the field, be ready to teach in the field of Late Imperial and Modern China, and be able to talk about history as a critical discipline.

### Readings

Every week all of us will do shared readings together, which is normally one monograph written in English. In addition, you will read individually assigned items, depending on your choice. Please expect to read an average of 300-400 pages per week.

### Weekly Postings

Each week, you will write a short response post (2 pages, double-spaced) addressing readings. Your paper should include: 1) a summary of the main points e.g., the thesis of the book and/or sub- theses and 2) a critical analysis of one point that interests you the most. Make sure to use the questions I put on the syllabus as a guide. The second part should be a reflective account meant to interrogate the author’s arguments rather than just summarize what you read.

### Presentation

Every week students will lead the discussion on the topic you have chosen.

### Grades

Your final grade will be calculated on a holistic consideration of your performance in discussions, forum posts and final papers, and in-class presentations.

### Requirements

1.Weekly Postings (40%) Post your opinions on the readings by Sunday@11:55pm before our Monday class

2.Class Presentation and Discussion (40%)

3.Final Paper (20%)


### 课程安排

Week 1 Introduction: How to Study Modern China?

READINGS:

➤ James Millward, “We need a new approach to teaching modern Chinese history” (2020) A review of Klaus Mühlhahn, Making China Modern. Harvard University Press, 736 pp, £31.95, January 2019, ISBN 9780674737358.

https://jimmillward.medium.com/we-need-a-new-approach-to-teaching-modern-chinese-history-we-have-lazily-repeated-false-d24983bd7ef2

DISCUSSION QUESTIONS:

1) What does the term “China” mean in this article? 

2) What are some key themes that China scholars often choose to cover modern China? 

3) What is the background of this article? How to best understand this polemic review?

Week 2 Understanding “China”

READINGS:

➤ Tang Xiaobing, Global Space and the Nationalist Discourse of Modernity: The Historical Thinking of Liang Qichao (Stanford University Press, 1996).

➤ Nicolas Tackett, The Origins of the Chinese Nation: Song China and the Forging of an East Asian World Order (Cambridge University press, 2017).

➤ Ge Zhaoguang, What Is China? Territory, Ethnicity, Culture, and History (Harvard University Press, 2018).

➤ Li Huaiyin, Reinventing Modern China: Imagination and Authenticity in Chinese Historical Writing (University of Hawaii Press, 2013) and Li Huaiyin, The Making of the Modern Chinese State, 1600-1950, (Routledge, 2020).

➤ Thomas Mullaney, Critical Han Studies (University of California Press, 2012) and Thomas Mullaney, Coming to Terms with the Nation (University of California Press, 2010).

DISCUSSION QUESTIONS:

1) What are some key historical moments in the development of the concept of “China”? 

2) In Tackett’s narrative, what does the term “Han” mean? Was “China” related to “Han”? 

3) How does that relationship change over time?

Week 3 The “New Qing History”

READINGS:

➤ Pamela Crossley, A Translucent Mirror: History and Identity in Qing Imperial Ideology (University of California Press, 2002) AND https://www.jeremiahjenne.com/the-archives/2018/4/8/chinese-academy-of-social-sciences-throwing-shade-at-the-new-qing-history AND https://www.suduri.net/comment.shtml especially “Nihilist for a Day!”

➤ Pamela Crossley, Orphan Warriors: Three Manchu Generations and the End of the Qing World (Princeton University Press, 1991).

➤ Ping-ti Ho, “The Significance of the Ch’ing Period in Chinese History,” JAS 26. 2 (1967):189-195. Evelyn Rawski, “Presidential Address: Re-envisioning the Qing: The Significance of the Qing Period in Chinese History,” JAS 55.4 (1996): 829-850 and Ping-Ti Ho, “In Defense of Sinicization: A Rebuttal of Evelyn Rawski’s “Re-envisioning the Qing,” JAS, 57.1 (1998): 123-155.

➤ Mark Elliot, The Manchu Way: The Eight Banners and Ethnic Identity in Late Imperial China (Stanford University Press, 2001).

➤ Edward Rhoads, Manchus and Han: Ethnic Relations and Political Power in Late Qing and Early Republican China, 1861-1928 (University of Washington Press, 2000).

➤ Evelyn Rawski, Early Modern China and Northeast Asia: Cross-Border Perspectives (Cambridge University Press, 2005).

DISCUSSION QUESTIONS:

1) What are the historical evidences used by scholars to support their divergent understandings of Qing history? 

2) Is there really a “New Qing History”? Who are promoting this label and for what purposes? 

3) How do we understand the field of Qing history?

Week 4 Border, Ethnicity and China from an Empire to a Nation

READINGS:

➤ Peter Purdue, China Marches West: The Qing Conquest of Central Eurasia (Harvard University Press, 2010).

➤ James Millward, Beyond the Pass: Economy, Ethnicity, and Empire in Qing Central Asia, 1759-1864 (Stanford University, 2016).

➤ Gail Hershatter et al. ed., Remapping China: Fissures in Historical Terrain (Stanford University Press, 1996).

➤ Judd Kinzley, Natural Resources and the New Frontier: Constructing Modern China’s Borderlands (University of Chicago Press, 2018).

➤ Eric Schluessel, Land of Strangers: The Civilizing Project in Qing Central Asia (Columbia University Press, 2020).

➤ Wang Yi, Transforming Inner Mongolia: Commerce, Migration, and Colonization on the Qing Frontier (Rowman and Littlefield, 2021).

DISCUSSION QUESTIONS:

1) How to best study the history of Xinjiang? 

2) What are some of the dominant paradigms in studying Xinjiang? 

3) How do scholars understand the concept of “nation” and apply this concept in their study?

Week 5 Encountering the West

READINGS:

➤ Lydia Liu, The Clash of Empires: The Invention of China in Modern World Making (Harvard University Press, 2004) AND Stuart Hall: “The West and the Rest: Discourse and Power,” in Modernity: An Introduction to Modern Society, 184-227.

➤ Lydia Liu ed., Tokens of Exchange: The Problem of Translation in Global Circulations (Duke University Press, 1999).

➤ Matthew Mosca, From Frontier Policy to Foreign Policy: The Question of India and the Transformation of Geopolitics in Qing China (Stanford University Press, 2013).

➤ Chen Li, Chinese Law in Imperial Eyes: Sovereignty, Justice, and Transcultural Politics (Columbia University Press, 2015).

➤ James Hevia, English Lessons: The Pedagogy of Imperialism in Nineteenth-Century China (Duke University Press, 2003) and James Hevia, Cherishing Men from Afar: Qing Guest Ritual and the Macartney Embassy of 1793 (Duke University Press, 1995).

➤ 茅海建: 天朝的崩溃 (三联出版社, 1997).

➤ 岸本美绪: 明清交替と江南社会 17世纪中国の秩序问题 (东京大学出版会, 1999).

DISCUSSION QUESTIONS:

1) How have different theories such as Post-Colonialism and Orientalism changed the field of modern Chinese history? 

2) Different approaches of Chinese, Japanese, and American scholars in studying Chinese diplomacy? 

3) How can we go beyond the realization of “The West and the Rest” and better study China?

Week 6 Chinse Scholars and the Fairbank School

READINGS:

➤ Ch’ü T’ung-tsu, Law and Society in Traditional China (Mouton, 1961) AND Introduction of John K. Fairbank, ed. Chinese Thought and Institutions (University of Chicago Press, 1957).

➤ Chang Chung-li, The Chinese Gentry (University of Washington Press, 1955).

➤ Ch’ü T’ung-tsu, Local Government in China Under the Ch’ing (Harvard University Press, 1962). 

➤ Ho Ping’ti, The Ladder of Success in Imperial China (Columbia University, 1962).

➤ Yang Ching-kin, Religion in Chinese Society: A study of Contemporary Social Function of Religion and Some of Their Historical Factor (University of California Press, 1968).

➤ John K. Fairbank, Trade and Diplomacy on The China Coast (Harvard University Press, 1953), John K. Fairbank, Edwin Reischauer, and Albert Craig A History of East Asian Civilization Volume One: East Asia the Great Tradition and Volume Two: East Asia the Modern Transformation (Charles E. Tuttle Co, 1966), John K. Fairbank, The Chinese World Order: Traditional China’s Foreign Relations (Harvard University Press, 1968) and John K. Fairbank, The Missionary Enterprise in China and America (Harvard University Press, 1974).

➤ Joseph Levenson, Confucian China and Its Modern Fate (1958-1965) (University of California Press, 1958-1965).

➤ Benjamin Schwartz, In Search of Wealth and Power: Yen Fu and the West (Harvard University Press, 1964).

DISCUSSION QUESTIONS:

Think about the methodologies used by scholars of this generation and think about the politics of Area Studies.

Week 7 Challenges from the Radicals and Fairbank School 2.0

READINGS:

➤ Fabio Lanza, The End of Concern: Maoist China, Activism, and Asian Studies (Duke University Press, 2017) AND Joseph Esherick, “Harvard on China: Apologetics of Imperialism” (1972).

➤ Maurice Meisner, Li Ta-Chao and the Origins of Chinese Marxism (Harvard University Press, 1967), Maurice Meisner, Mao’s China and After: A History of the People’s Republic. (Free Press, 3rd ed., 1999), and Maurice Meisner, The Deng Xiaoping Era: An Inquiry into the Fate of Chinese Socialism, 1978-1994. (Hill and Wang, 1996).

➤ Paul Pickowicz, Marxist Literary Thought in China: The Influence of Ch’u Ch’iu-pai (University of California Press, 1981), Paul Pickowicz, Marxist Literary Thought and China: A Conceptual Framework (Center for Chinese Studies, 1980), Paul Pickowicz, Edward Friedman and Mark Selden, Chinese Village, Socialist State (Yale University Press, 1991) and Paul Pickowicz, Edward Friedman and Mark Selden, Revolution, Resistance, and Reform in Village China (Yale University Press, 2005).

➤ Joseph Esherick, Reform and Revolution: The 1911 Revolution in Hunan and Hubei (University of California Press, 1976).

➤ Philip Kuhn, Soulstealers: The Chinese Sorcery Scare of 1768 (Harvard University Press, 1992) and Philip Kuhn, Origins of the Modern Chinese State (Stanford University Press, 2002).

DISCUSSION QUESTIONS:

How have leftist scholars viewed Mao’s China and the Chinese revolution? How have their views changed over time?

Week 8 The California School: Local History, Legal History, and Global History

READINGS:

➤ Madeleine Yue Dong, Republican Beijing: The City and Its Histories (University of California Press, 2003).

➤ Philip Huang, The Peasant Economy and Social Change in North China (Stanford University Press, 1985) and Philip Huang, Civil Justice in China: Representation and Practice in the Qing (Stanford University Press, 1996).

➤ Mathew Sommer, Sex, Law, and Society in late Imperial China (Stanford University Press, 2000).

➤ Bradly Reed, Talons and Teeth: County Clerks and Runners in the Qing Dynasty (Stanford University Press, 2000).

➤ Margret Kuo, Intolerable Cruelty: Marriage, Law, and Society in Early Twentieth-Century China (Rowman and Littlefield, 2012).

➤ Joseph Esherick, The Origins of the Boxer Uprising (University of California Press, 1987).

➤ Kenneth Pomeranz, The Great Divergence: China, Europe, and the Making of the Modern World Economy (Princeton University Press, 2000).

➤ Frederick Wakeman, Policing Shanghai, 1927-1937 (University of California Press, 1996).

➤ Madeline Zelin, The Merchants of Zigong, Industrial Entrepreneurship in Early Modern China (Columbia University Press, 2005).

➤ Yeh Wen-hsin, Shanghai Splendor: Economic Sentiments and the Making of Modern China, 1843-1949 (University of California Press, 2008).

DISCUSSION QUESTIONS:

The California school challenges the framework of nation-states and writes history of different scales. What are some of their most important contributions?

Week 9 Understanding Moralities, Emotions, and Gender in Chinese History

READINGS:

➤ Haiyan Lee, The Stranger and the Chinese Moral Imagination (Stanford University Press, 2015) OR Emily Baum, The Invention of Madness: State, Society, and the Insane in Modern China (University of Chicago Press, 2018).

➤ Richard Madsen, Morality and Power in a Chinese Village (University of California Press, 1984).

➤ Bryna Goodman, The Suicide of Miss Xi: Democracy and Disenchantment in the Chinese Republic (Harvard University Press, 2021).

➤ Dorothy Ko, Cinderella’s Sisters: A Revisionist History of Footbinding (University of California, 2005) and Dorothy Ko, Teachers of the Inner Chambers: Women and Culture in Seventeenth-century China (Stanford University Press, 1994).

➤ Joan Judge, The Precious Raft of History: The Past, the West, and the Woman Question in China (Stanford University Press, 2008) and Joan Judge, Republican Lens: Gender, Visuality, and Experience in the Early Chinese Periodical Press (University of California Press, 2015).

➤ Hu Ying, Tales of Translation: Composing the New Woman in China, 1898-1918 (Stanford University Press, 2000).

➤ Tani Barlow, In the Event of Women (Duke University Press, 2022) and Tani Barlow, The Question of Women in Chinese Feminism (Duke University Press, 2004).

➤ Gail Hershatter, Women in China’s Long Twentieth Century (University of California Press, 2007), Gail Hershatter ed., Guide to Women’s Studies in China (Center for Chinese Studies, 1998) and Gail Hershatter and Wang Zheng, “Chinese History: A Useful Category of Gender Analysis,” AHR, 113. 5 (2008): 1404-1421.

➤ Emily Honig, Sisters and Strangers: Women in the Shanghai Cotton Mills, 1919-1949 (Stanford University Press, 1992).

➤ Susan Mann, The Talented Women of the Zhang Family (University of California Press, 2007) and Susan Mann, Gender and Sexuality in Modern Chinese History (Cambridge University Press, 2011).

DISCUSSION QUESTIONS:

What sources have these authors used in exploring the above subject matters? Are you convinced or inspired by their methodologies and approaches?

Week 10 History of Science and History of Medicine

READINGS:

➤ Sigrid Schmalzer, Red Revolution, Green Revolution: Scientific Farming in Socialist China (University of Chicago Press, 2016) Listen to the podcast here (http://newbooksnetwork.com/sigrid-schmalzer-red-revolution-green-revolution-scientific-farming-in-socialist-china-university-of-chicago-press-2016/).

➤ Bian He, Know Your Remedies: Pharmacy and Culture in Early Modern China (Princeton University Press, 2021).

➤ Sigrid Schmalzer, The People’s Peking Man: Popular Science and Human Identity in Twentieth-Century China (University of Chicago Press, 2008).

➤ Ruth Rogaski, Hygienic Modernity: Meanings of Health and Disease in Treaty-Port China (University of California Press, 2014).

➤ Miriam Gross, Farewell to the God of Plague Chairman Mao’s Campaign to Deworm China (University of California Press, 2016).

DISCUSSION QUESTIONS:

Who are the main protagonists in Schmalzer’s story? Does the study of History of Science and History of Medicine bring us a different periodization of modern China?

